### ISSUE TITLE
Opgaver

### ISSUE THREAD

**Issue by AndreaRyholt** [LasseThomsenSkole/ProjektKalkulation#10]
Som bruger vil jeg gerne kunne oprette opgaver indenunder delprojekter, så delprojekter bliver mere overskuelige.

**Comment by LasseThomsenSkole** [comment]
Som bruger ønsker jeg at kunne oprette nye opgaver (**_tasks_**) under mine projekter, så jeg kan angive specifikke arbejdsopgaver.
