### ISSUE TITLE
Brugergrænseflade

### ISSUE THREAD

**Issue by AndreaRyholt** [LasseThomsenSkole/ProjektKalkulation#16]
Som bruger vil jeg gerne have en brugergrænseflade, hvor man kan oprette og vedligeholde et projekt, så der er overblik over projekter.

**Comment by LasseThomsenSkole** [comment]
Som bruger ønsker jeg at kunne markere opgaver som færdiggjort, så jeg kan holde styr på fremskridtet i mine projekter.
