### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by LasseThomsenSkole** [LasseThomsenSkole/ProjektKalkulation#21]
Som bruger vil jeg gerne have en specifik side med vejledning til fejlkoder, så jeg nemt kan finde ud af problemet og løse det.

**Comment by AndreaRyholt** [comment]
Fra lektion:

[Spring boot - error handling.pdf](https://github.com/LasseThomsenSkole/ProjektKalkulation/files/15175208/Spring.boot.-.error.handling.pdf)



https://www.codejava.net/frameworks/spring-boot/spring-boot-error-handling-guide
