### ISSUE TITLE
Opret profil

### ISSUE THREAD

**Issue by hantamil** [LasseThomsenSkole/ProjektKalkulation#9]
Som administrator ønsker jeg at kunne oprette og administrere brugerkonti, så teammedlemmer kan logge ind og få adgang til projektdataene.

**Comment by LasseThomsenSkole** [comment]
evt. bruge BCrypt til at hashe passwords og Spring Security for authentication

**Comment by LasseThomsenSkole** [comment]
Som administrator ønsker jeg at kunne oprette og administrere brugerkonti, så teammedlemmer kan logge ind og få adgang til projektdataene.
